# Generated by Django 5.0.7 on 2024-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(),
        ),
    ]
