# Generated by Django 5.0.7 on 2024-08-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_alter_outflow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
