# Generated by Django 5.0.7 on 2024-08-17 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0003_alter_outflow_description'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='products.product'),
        ),
    ]
