# Generated by Django 5.0.7 on 2024-08-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_pedido_cliente_orders_delete_itempedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
